name: Deploy Site

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  hetzner:
    name: Hetzner
    runs-on: ubuntu-latest
    environment: hetzner-prod
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Deploy via SFTP
        uses: milanmk/actions-file-deployer@b204fec5b826c391b116c40b789df470a4fb6870 # 1.18
        with:
          remote-protocol: "sftp"
          remote-host: ${{ secrets.REMOTE_HOST }}
          remote-user: ${{ secrets.REMOTE_USER }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-path: ${{ secrets.REMOTE_TARGET }}
          local-path: ./dist/
          artifacts: true
          sync-delta-excludes: |
            *.git
            .htaccess
            .htpasswd
