name: Deploy Site

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  hetzner:
    name: Hetzner
    runs-on: ubuntu-latest
    environment: hetzner-prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Deploy via SFTP
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          ARGS: "-rlgoDzvc -i --delete -n"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "dist/"
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: ".htaccess,.git/,.well-known/acme-challenge/"

