name: Deploy Site

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  hetzner:
    name: Hetzner
    runs-on: ubuntu-latest
    environment: hetzner-prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Deploy via SFTP
        uses: Dylan700/sftp-upload-action@v1.2.3
        with:
          server: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          dry-run: true
          delete: true
          uploads: |
            ./dist/ => ${{ secrets.REMOTE_TARGET }}
          ignore: |
            *.git
            .htaccess
            .htpasswd
