name: Deploy Site

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  hetzner:
    name: Hetzner
    runs-on: ubuntu-latest
    environment: hetzner-prod
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Deploy via SFTP
        uses: milanmk/actions-file-deployer@b204fec5b826c391b116c40b789df470a4fb6870 # 1.18
        with:
          remote-protocol: "sftp"
          remote-host: ${{ secrets.REMOTE_HOST }}
          remote-user: ${{ secrets.REMOTE_USER }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-path: ${{ secrets.REMOTE_TARGET }}
          local-path: ${{ github.workspace }}/dist/
          sync: "full"
          artifacts: true
