name: Deploy Site

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  hetzner:
    name: Hetzner
    runs-on: ubuntu-latest
    environment: hetzner-prod
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Deploy via SFTP
        uses: Dylan700/sftp-upload-action@50ed7273493353a60dace713957c36b02dd87bec # v1.2.3
        with:
          server: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          uploads: |
            ./dist/ => ${{ secrets.REMOTE_TARGET }}
          ignore: |
            *.git
            .htaccess
            .htpasswd
